require_relative('../models/customers')
require_relative('../models/films')
require_relative('../models/tickets')
require_relative('../models/screenings')

require('pry-byebug')

Ticket.delete_all()
Customer.delete_all()
Film.delete_all()
Screening.delete_all()

customer1 = Customer.new({'name' => 'Louise', 'funds' => 20})
customer2 = Customer.new({'name' => 'Steve', 'funds' => 25})
customer3 = Customer.new({'name' => 'Jo', 'funds' => 15})
customer4 = Customer.new({'name' => 'Alanna', 'funds' => 10})
customer5 = Customer.new({'name' => 'Fred', 'funds' => 12})
customer6 = Customer.new({'name' => 'Ruth', 'funds' => 10})
customer7 = Customer.new({'name' => 'Rachel', 'funds' => 15})
customer8 = Customer.new({'name' => 'John', 'funds' => 10})
customer9 = Customer.new({'name' => 'Lynsey', 'funds' => 10})
customer10 = Customer.new({'name' => 'Craig', 'funds' => 9})
customer11= Customer.new({'name' => 'Chris', 'funds' => 10})
customer12= Customer.new({'name' => 'Hayley', 'funds' => 10})

customer1.save()
customer2.save()
customer3.save()
customer4.save()
customer5.save()
customer6.save()
customer7.save()
customer8.save()
customer9.save()
customer10.save()
customer11.save()
customer12.save()


film1 = Film.new({'title' => 'IT', 'price' => 8})
film2 = Film.new({'title' => 'T2', 'price' => 5})
film3 = Film.new({'title' => 'The Lion King', 'price' => 3})
film4 = Film.new({'title' => 'Dunkirk', 'price' => 5})

film1.save()
film2.save()
film3.save()
film4.save()

ticket1 = Ticket.new({'customer_id' => customer1.id, 'film_id' => film1.id})
ticket2 = Ticket.new({'customer_id' => customer2.id, 'film_id' => film2.id})
ticket3 = Ticket.new({'customer_id' => customer3.id, 'film_id' => film3.id})
ticket4 = Ticket.new({'customer_id' => customer4.id, 'film_id' => film4.id})
ticket5 = Ticket.new({'customer_id' => customer1.id, 'film_id' => film2.id})
ticket6 = Ticket.new({'customer_id' => customer3.id, 'film_id' => film1.id})
ticket7 = Ticket.new({'customer_id' => customer4.id, 'film_id' => film1.id})
ticket8 = Ticket.new({'customer_id' => customer5.id, 'film_id' => film4.id})
ticket9 = Ticket.new({'customer_id' => customer6.id, 'film_id' => film4.id})
ticket10 = Ticket.new({'customer_id' => customer7.id, 'film_id' => film3.id})
ticket11 = Ticket.new({'customer_id' => customer8.id, 'film_id' => film3.id})
ticket12= Ticket.new({'customer_id' => customer9.id, 'film_id' => film3.id})
ticket13 = Ticket.new({'customer_id' => customer10.id, 'film_id' => film1.id})
ticket14 = Ticket.new({'customer_id' => customer11.id, 'film_id' => film2.id})
ticket15 = Ticket.new({'customer_id' => customer12.id, 'film_id' => film4.id})


ticket1.save()
ticket2.save()
ticket3.save()
ticket4.save()
ticket5.save()
ticket6.save()
ticket7.save()
ticket8.save()
ticket9.save()
ticket10.save()
ticket11.save()
ticket12.save()
ticket13.save()
ticket14.save()
ticket15.save()

screening1 = Screening.new({'time_of_screening' => '21.00', 'film_id' => film1.id})
screening2 = Screening.new({'time_of_screening' => '21.30', 'film_id' => film1.id})
screening3 = Screening.new({'time_of_screening' => '22.30', 'film_id' => film1.id})
screening4 = Screening.new({'time_of_screening' => '19.30', 'film_id' => film2.id})
screening5 = Screening.new({'time_of_screening' => '21.00', 'film_id' => film2.id})
screening6 = Screening.new({'time_of_screening' => '22.30', 'film_id' => film2.id})
screening7 = Screening.new({'time_of_screening' => '15.30', 'film_id' => film3.id})
screening8 = Screening.new({'time_of_screening' => '17.30', 'film_id' => film3.id})
screening9 = Screening.new({'time_of_screening' => '18.45', 'film_id' => film3.id})
screening10 = Screening.new({'time_of_screening' => '18.45', 'film_id' => film4.id})
screening11 = Screening.new({'time_of_screening' => '20.00', 'film_id' => film4.id})
screening12 = Screening.new({'time_of_screening' => '20.45', 'film_id' => film4.id})

screening1.save()
screening2.save()
screening3.save()
screening4.save()
screening5.save()
screening6.save()
screening7.save()
screening8.save()
screening9.save()
screening10.save()
screening11.save()
screening12.save()

binding.pry
nil
